INSTALL_DIR := /usr/local/bin
SCRIPT_NAME := json_to_csv
SCRIPT_NAME_EXT := $(SCRIPT_NAME).py
INSTALL_PATH := $(INSTALL_DIR)/$(SCRIPT_NAME)

all: install

install: $(INSTALL_PATH)

$(INSTALL_PATH): $(SCRIPT_NAME_EXT)
	install $(SCRIPT_NAME_EXT) $(INSTALL_PATH)

